config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: "admin/sessions"}

  scope module: :admin, path: :admins, as: :admins do
    root to: "homes#index", as: :admin_root
    resources :admins
  end

  devise_for :users, controllers: {sessions: "user/sessions"}

  scope module: :user do
    root to: "homes#index"
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  enum gender_id: {male: 1, female: 2}

  validates :name, :address, :phone_number, presence: true
  validates :phone_number, numericality: {only_integer: true}
  validates :birthday, valid_date: true, presence: true
  validates :email, presence: true, format_rule: true, uniqueness: {case_sensitive: false}
  attr_accessor :skip_password_validation

  ADMIN_ATTRIBUTES = [
    :email, :name, :birthday, :gender_id, :address, :phone_number
  ]

  def self.option_for_gender_id
    self.gender_ids.keys.map{|key, _| [I18n.t("admin.info.gender_ids.#{key}"), key]}
  end

  private
  def password_required?
    !skip_password_validation
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid

  validates :name, :avatar, :status_id, presence: true
  validates :name, uniqueness: {case_sensitive: false}
end

app/models/color.rb
class Color < ApplicationRecord
  acts_as_paranoid
end

app/models/image.rb
class Image < ApplicationRecord
  acts_as_paranoid
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid
end

app/models/size.rb
class Size < ApplicationRecord
  acts_as_paranoid
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  acts_as_paranoid
end

app/models/tag.rb
class Tag < ApplicationRecord
  acts_as_paranoid
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  acts_as_paranoid

  enum gender_id: {male: 1, female: 2}

  validates :name, uniqueness: {case_sensitive: false}
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout "layouts/admin/base"
  before_action :authenticate_admin!
  before_action :set_default_locale

  private
  def set_default_locale
    I18n.locale = :vi
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::BaseController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  def subdomain_redirect
    case request.subdomain
    when Settings.domain.staff
      redirect_to staff_root_path locale: LocaleConstraint::DEFAULT_LANGUAGE
    else
      redirect_to root_path locale: LocaleConstraint::DEFAULT_LANGUAGE
    end
  end
end

app/controllers/concerns/accessible.rb
module Accessible
  extend ActiveSupport::Concern
  included do
    before_action :check_user
  end

  protected
  def check_user
    if current_admin
      flash.clear
      redirect_to(admins_admin_root_path) && return
    elsif current_user
      flash.clear
      redirect_to(root_path) && return
    end
  end
end

app/controllers/staff/base_controller.rb
class Staff::BaseController < ApplicationController
  protect_from_forgery

  include Mltilanguage

  before_action :set_locale, default_url_options

end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
  layout "layouts/user/base"
  before_action :set_default_locale

  private
  def set_default_locale
    I18n.locale = :vi
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < User::BaseController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admins/_form.html.erb
<div class="form-group row">
  <%= f.label :email, class: "col-md-3 control-label required" %>
  <div class="col-md-9">
    <%= f.text_field :email, class: "form-control", tabindex: 1 %>
  </div>
</div>
<div class="form-group row">
  <%= f.label :name, class: "col-md-3 control-label required" %>
  <div class="col-md-9">
    <%= f.text_field :name, class: "form-control", tabindex: 2 %>
  </div>
</div>
<div class="form-group row">
  <%= f.label :birthday, class: "col-md-3 control-label required" %>
  <div class="col-md-9">
  <%= f.text_field :birthday, class: 'form-control', id: "birthday-datepicker" %>
  </div>
</div>
<div class="form-group row">
  <%= f.label :gender_id, class: "col-md-3 control-label required" %>
  <div class="col-md-9">
    <%= f.select :gender_id, Admin.option_for_gender_id , {include_blank: false}, class: "form-control", tabindex: 4 %>
  </div>
</div>
<div class="form-group row">
  <%= f.label :address, class: "col-md-3 control-label required" %>
  <div class="col-md-9">
    <%= f.text_field :address, class: "form-control", tabindex: 5 %>
  </div>
</div>
<div class="form-group row">
  <%= f.label :phone_number, class: "col-md-3 control-label required" %>
  <div class="col-md-9">
    <%= f.text_field :phone_number, class: "form-control", tabindex: 6 %>
  </div>
</div>
<a class="btn btn-primary" tabindex="9" data-toggle="modal" data-target="#confirm-modal">
  <%= t "button.save" %>
</a>

<%= render "shared/modal_submit_confirm", title_confirm: t("modal_confirm.title_save_confirm"),
  content_confirm: t("modal_confirm.content_not_send_email").html_safe, submit_modal_id: "submit-save-admin",
  button_color: "primary" %>

app/views/admin/admins/index.html.erb
index
 admin

app/views/admin/admins/new.html.erb
<%= content_for :page_title, "Admin" %>
<%= content_for :sub_title, "New admin" %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@admin, url: admins_admins_path, class: "form-horizontal", id: "new-admin") do |f| %>
      <%= render "form", f: f %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<aside id="footer-widgets" class="widget-area" role="complementary">
  <div class="container">
    <div class="inner-wrapper">
      <div class="widget-column footer-active-3">
        <section id="text-2" class="widget widget_text">
          <h2 class="widget-title">About eCommerce Gem</h2>
          <div class="textwidget">
            <p>Nunc et ornare tellus. Quisque imperdiet interdum commodo. Integer laoreet tristique neque quis laoreet. Duis ut ultrices est, sed feugiat leo.</p>
          </div>
        </section>
        <section id="ecommerce-gem-social-2" class="widget ecommerce_gem_widget_social">
          <div class="menu-social-menu-container">
            <ul id="menu-social-menu-1" class="menu">
              <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5"><a target="_blank" href="https://www.facebook.com/promenadethemes/"><span class="screen-reader-text">Facebook</span></a></li>
              <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6"><a target="_blank" href="https://twitter.com/promenadetheme"><span class="screen-reader-text">Twitter</span></a></li>
              <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-132"><a target="_blank" href="https://www.youtube.com/channel/UCgEOUr3qjSQmJ9d5x1DKFrg/videos"><span class="screen-reader-text">Youtube</span></a></li>
            </ul>
          </div>
        </section>
      </div>
      <div class="widget-column footer-active-3">
        <section id="ecommerce-gem-contact-2" class="widget ecommerce_gem_widget_contact">
          <div class="contact-list">
            <h2 class="widget-title">Contact Us</h2>
            <div class="contact-wrapper">
              <div class="contact-item">
                <div class="contact-inner">
                  <span class="contact-icon">
                  <span class="icon-map"></span>
                  </span>
                  <div class="contact-text-wrap">
                    <p>Bansbari-03, Kathmandu</p>
                  </div>
                  <!-- .contact-text-wrap -->
                </div>
              </div>
              <!-- .contact-item -->
              <div class="contact-item">
                <div class="contact-inner">
                  <span class="contact-icon">
                  <span class="icon-envelope"></span>
                  </span>
                  <div class="contact-text-wrap">
                    <p>info@promenadethemes.com</p>
                  </div>
                  <!-- .contact-text-wrap -->
                </div>
              </div>
              <!-- .contact-item -->
              <div class="contact-item">
                <div class="contact-inner">
                  <span class="contact-icon">
                  <span class="icon-mobile"></span>
                  </span>
                  <div class="contact-text-wrap">
                    <p>+977-1-2344478</p>
                  </div>
                  <!-- .contact-text-wrap -->
                </div>
              </div>
              <!-- .contact-item -->
              <div class="contact-item">
                <div class="contact-inner">
                  <span class="contact-icon">
                  <span class="icon-global"></span>
                  </span>
                  <div class="contact-text-wrap">
                    <p>https://promenadethemes.com</p>
                  </div>
                  <!-- .contact-text-wrap -->
                </div>
              </div>
              <!-- .contact-item -->
            </div>
          </div>
          <!-- .features-list -->
        </section>
      </div>
      <div class="widget-column footer-active-3">
        <section id="ecommerce-gem-features-2" class="widget ecommerce_gem_widget_features">
          <div class="features-list">
            <div class="features-wrapper">
              <div class="feature-item feature-item-one">
                <div class="feature-inner">
                  <span class="feature-icon">
                  <span class="icon-refresh"></span>
                  </span>
                  <div class="feature-text-wrap">
                    <h2 class="feature-title">Free Shipping &amp; Return</h2>
                    <p>Free shipping on all orders above $99</p>
                  </div>
                  <!-- .feature-text-wrap -->
                </div>
              </div>
              <!-- .feature-item -->
              <div class="feature-item feature-item-two">
                <div class="feature-inner">
                  <span class="feature-icon">
                  <span class="icon-wallet"></span>
                  </span>
                  <div class="feature-text-wrap">
                    <h2 class="feature-title">Money Back Guarantee</h2>
                    <p>100% money back guarantee</p>
                  </div>
                  <!-- .feature-text-wrap -->
                </div>
              </div>
              <!-- .feature-item -->
              <div class="feature-item feature-item-three">
                <div class="feature-inner">
                  <span class="feature-icon">
                  <span class="icon-chat"></span>
                  </span>
                  <div class="feature-text-wrap">
                    <h2 class="feature-title">24/7 Online Support</h2>
                    <p>Support staffs ready to help you</p>
                  </div>
                  <!-- .feature-text-wrap -->
                </div>
              </div>
              <!-- .feature-item -->
            </div>
          </div>
          <!-- .features-list -->
        </section>
      </div>
    </div>
    <!-- .inner-wrapper -->
  </div>
  <!-- .container -->
</aside>

app/views/layouts/_header.html.erb
<header id="masthead" class="site-header" role="banner">
  <div class="container">
    <div class="head-wrap">
      <div class="site-branding">
        <h1 class="site-title"><a href="https://promenadethemes.com/demo/ecommerce-gem/" rel="home">eCommerce Gem</a></h1>
        <p class="site-description">Multipurpose e-Commerce WP Theme</p>
      </div>
      <!-- .site-branding -->
      <div id="main-nav" class="clear-fix">
        <nav id="site-navigation" class="main-navigation" role="navigation">
          <div class="wrap-menu-content">
            <div class="menu-main-menu-container">
              <ul id="primary-menu" class="menu">
                <li id="menu-item-9" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-7 current_page_item menu-item-9"><a href="https://promenadethemes.com/demo/ecommerce-gem/">Home</a></li>
                <li id="menu-item-93" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-93">
                  <a href="https://promenadethemes.com/demo/ecommerce-gem/shop/">Shop</a>
                  <ul class="sub-menu">
                    <li id="menu-item-176" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-176"><a href="https://promenadethemes.com/demo/ecommerce-gem/product-category/accessories/">Accessories</a></li>
                    <li id="menu-item-217" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-217"><a href="https://promenadethemes.com/demo/ecommerce-gem/product-category/casual/">Casual</a></li>
                    <li id="menu-item-173" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-173"><a href="https://promenadethemes.com/demo/ecommerce-gem/product-category/clothing/">Clothing</a></li>
                    <li id="menu-item-175" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-175"><a href="https://promenadethemes.com/demo/ecommerce-gem/product-category/men/">Men</a></li>
                    <li id="menu-item-174" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-174"><a href="https://promenadethemes.com/demo/ecommerce-gem/product-category/women/">Women</a></li>
                  </ul>
                </li>
                <li id="menu-item-92" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-92">
                  <a href="https://promenadethemes.com/demo/ecommerce-gem/my-account/">My account</a>
                  <ul class="sub-menu">
                    <li id="menu-item-90" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-90"><a href="https://promenadethemes.com/demo/ecommerce-gem/cart/">Cart</a></li>
                    <li id="menu-item-91" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-91"><a href="https://promenadethemes.com/demo/ecommerce-gem/checkout/">Checkout</a></li>
                    <li id="menu-item-218" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-218"><a href="https://promenadethemes.com/demo/ecommerce-gem/wishlist/">Wishlist</a></li>
                  </ul>
                </li>
                <li id="menu-item-89" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89"><a href="https://promenadethemes.com/demo/ecommerce-gem/blog/">Blog</a></li>
                <li id="menu-item-184" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-184"><a href="https://promenadethemes.com/demo/ecommerce-gem/contact-us/">Contact Us</a></li>
              </ul>
            </div>
          </div>
          <!-- .menu-content -->
        </nav>
        <!-- #site-navigation -->
      </div>
      <!-- #main-nav -->
    </div>
  </div>
  <!-- .container -->
</header>

app/views/layouts/_topbar.html.erb
<div id="top-bar" class="top-header">
  <div class="container">
    <div class="top-left">
      <div class="top-left-inner">
        <span class="address"><i class="fa fa-map-marker" aria-hidden="true"></i> Kathmandu, Nepal</span>
        <span class="phone"><i class="fa fa-phone" aria-hidden="true"></i> +977-1-33445566</span>
        <span class="fax"><i class="fa fa-envelope-o" aria-hidden="true"></i> info@ecgem.com</span>
      </div>
    </div>

    <div class="top-right">
      <div class="top-social-menu menu-social-menu-container">
        <div class="widget ecommerce_gem_widget_social">
          <div class="menu-social-menu-container">
            <ul id="menu-social-menu" class="menu">
              <li id="menu-item-5" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5"><a target="_blank" href="https://www.facebook.com/promenadethemes/"><span class="screen-reader-text">Facebook</span></a></li>
              <li id="menu-item-6" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6"><a target="_blank" href="https://twitter.com/promenadetheme"><span class="screen-reader-text">Twitter</span></a></li>
              <li id="menu-item-132" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-132"><a target="_blank" href="https://www.youtube.com/channel/UCgEOUr3qjSQmJ9d5x1DKFrg/videos"><span class="screen-reader-text">Youtube</span></a></li>
            </ul>
          </div>
        </div>
      </div>

      <div class="top-account-wrapper logged-out">
        <a href="https://promenadethemes.com/demo/ecommerce-gem/my-account/">
          <i class="fa fa-user-o" aria-hidden="true"></i>
          <span class="top-log-in">Login / Register</span>
        </a>
      </div>

      <div class="top-wishlist-wrapper">
        <div class="top-icon-wrap">
          <a class="wishlist-btn" href="https://promenadethemes.com/demo/ecommerce-gem/wishlist/">
            <i class="fa fa-heart" aria-hidden="true"></i><span class="wish-value">0</span>
          </a>
        </div>
      </div>

      <div class="top-cart-wrapper">
        <div class="top-icon-wrap">
          <a href="https://promenadethemes.com/demo/ecommerce-gem/cart/">
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            <span class="cart-value ec-cart-fragment"> 0</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin/_sidebar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-padding">
  <a class="navbar-brand mr-auto" href="#">SAIYAN</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="fa fa-bell nav-item-link" href="#"></a>
        <span class="badge badge-notify badge-danger">1</span>
      </li>
      <li class="nav-item">
        <a class="fa fa-angellist nav-item-link" href="#"></a>
        <span class="badge badge-notify badge-success">1</span>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <img src="https://pbs.twimg.com/profile_images/833767319973212161/Ft904pMk_400x400.jpg" class="rounded-circle" height="40" width="40">
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-menu-custom" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Profile settings</a>
          <a class="dropdown-item" href="#">Change password</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Sign out</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<div class="row" id="body-row">
  <div id="sidebar-container" class="sidebar-expanded d-none d-md-block">
    <ul class="list-group">
      <a href="#submenu-category" data-toggle="collapse" aria-expanded="false" class="bg-dark list-group-item list-group-item-action flex-column align-items-start list-group-item-custom">
        <div class="d-flex w-100 justify-content-start align-items-center">
          <span class="fa fa-cubes fa-fw mr-2"></span>
          <span class="menu-collapsed">Category</span>
          <span class="submenu-icon ml-auto"></span>
        </div>
      </a>
      <div id='submenu-category' class="collapse sidebar-submenu">
        <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
        <span class="fa fa-angle-double-right fa-fw"></span>
        <span class="menu-collapsed">New category</span>
        </a>
        <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
        <span class="fa fa-angle-double-right fa-fw"></span>
        <span class="menu-collapsed">Category list</span>
        </a>
      </div>
      <a href="#submenu-subcategory" data-toggle="collapse" aria-expanded="false" class="bg-dark list-group-item list-group-item-action flex-column align-items-start list-group-item-custom">
        <div class="d-flex w-100 justify-content-start align-items-center">
          <span class="fa fa-cubes fa-fw mr-2"></span>
          <span class="menu-collapsed">Sub category</span>
          <span class="submenu-icon ml-auto"></span>
        </div>
      </a>
      <div id='submenu-subcategory' class="collapse sidebar-submenu">
        <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
        <span class="fa fa-angle-double-right fa-fw"></span>
        <span class="menu-collapsed">New sub category</span>
        </a>
        <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
        <span class="fa fa-angle-double-right fa-fw"></span>
        <span class="menu-collapsed">Sub category list</span>
        </a>
      </div>
      <a href="#submenu1" data-toggle="collapse" aria-expanded="false" class="bg-dark list-group-item list-group-item-action flex-column align-items-start list-group-item-custom">
        <div class="d-flex w-100 justify-content-start align-items-center">
          <span class="fa fa-user fa-fw mr-2"></span>
          <span class="menu-collapsed">Admins</span>
          <span class="submenu-icon ml-auto"></span>
        </div>
      </a>
      <div id='submenu1' class="collapse sidebar-submenu">
        <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
        <span class="fa fa-angle-double-right fa-fw"></span>
        <span class="menu-collapsed">New admin</span>
        </a>
        <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
        <span class="fa fa-angle-double-right fa-fw"></span>
        <span class="menu-collapsed">Admin list</span>
        </a>
      </div>
      <a href="#submenu2" data-toggle="collapse" aria-expanded="false" class="bg-dark list-group-item list-group-item-action flex-column align-items-start list-group-item-custom">
        <div class="d-flex w-100 justify-content-start align-items-center">
          <span class="fa fa-users fa-fw mr-2"></span>
          <span class="menu-collapsed">Users</span>
          <span class="submenu-icon ml-auto"></span>
        </div>
      </a>
      <div id='submenu2' class="collapse sidebar-submenu">
        <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
        <span class="fa fa-angle-double-right fa-fw"></span>
        <span class="menu-collapsed">New user</span>
        </a>
        <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
        <span class="fa fa-angle-double-right fa-fw"></span>
        <span class="menu-collapsed">User list</span>
        </a>
      </div>
      <a href="#" class="bg-dark list-group-item list-group-item-action list-group-item-custom">
        <div class="d-flex w-100 justify-content-start align-items-center">
          <span class="fa fa-tasks fa-fw mr-2"></span>
          <span class="menu-collapsed">Tasks</span>
        </div>
      </a>
      <a href="#" class="bg-dark list-group-item list-group-item-action list-group-item-custom">
        <div class="d-flex w-100 justify-content-start align-items-center">
          <span class="fa fa-calendar fa-fw mr-2"></span>
          <span class="menu-collapsed">Calendar</span>
        </div>
      </a>
      <a href="#" class="bg-dark list-group-item list-group-item-action list-group-item-custom">
        <div class="d-flex w-100 justify-content-start align-items-center">
          <span class="fa fa-question fa-fw mr-2"></span>
          <span class="menu-collapsed">Help</span>
        </div>
      </a>
      <a href="#" data-toggle="sidebar-colapse" class="bg-dark list-group-item list-group-item-action d-flex align-items-center list-group-item-custom">
        <div class="d-flex w-100 justify-content-start align-items-center">
          <span id="collapse-icon" class="fa fa-angle-double-left fa-fw mr-2"></span>
          <span id="collapse-text" class="menu-collapsed">Collapse</span>
        </div>
      </a>
    </ul>
  </div>
  <div class="col">
      <%= render "shared/flash" %>
    <div class="container">
      <% if content_for?(:page_title) %>
        <div class="content-main-page-header">
          <h2 class="main-page-title"><%= yield(:page_title) %></h2>
          <% if content_for?(:new_element) %>
            <%= link_to "New", yield(:new_element), class: "btn btn-sm btn-primary btn-new-element" %>
          <% end %>
          <% if content_for?(:back_link) %>
            <% back_link_label = content_for?(:back_link_label) ? yield(:back_link_label) : t("layout.header.back_to_list") %>
            <%= link_to back_link_label, yield(:back_link), class: "btn btn-sm btn-primary btn-back-to-list" %>
          <% end %>
        </div><br>
      <% end %>
      <% if content_for?(:sub_title) %>
        <h4 class="sub-page-title"><%= yield(:sub_title) %></h4><br>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saiyan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/admin/sidebar" %>
  </body>
</html>

app/views/layouts/admin/unauthenticated.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saiyan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <img src="http://file.vforum.vn/hinh/2018/03/hinh-anh-hinh-nen-songoku-dep-nhat-tu-nho-den-lon-19.jpg">
        </div>
        <div class="col-md-5">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saiyan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/topbar" %>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>